services:
  api:
    container_name: loan_simulator_api
    build: ./
    ports:
      - 8080:80
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_hackathon
    volumes:
      # Persistência dos dados
      - sql_data:/var/opt/mssql
      # Inicialização (para execução manual)
      - ./data:/initdb
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: keycloak_hackathon
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data

volumes:
  sql_data:
  keycloak_data:
