services:
  api:
    container_name: loan_simulator_api
    build: ./
    ports:
      - 8080:80
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_hackathon
    volumes:
      - ./data:/initdb
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"

  
  sqlserver-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_init_runner
    depends_on:
      - sqlserver
    volumes:
      - ./init.sh:/init.sh
    entrypoint: >
      bash -c "
        echo 'Aguardando SQL Server iniciar...';
        sleep 30;
        ./init.sh;
        echo 'Script init.sh executado com sucesso.'
      "
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8081:8080"
