// <auto-generated />
using System;
using Infrastructure.SqlServer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SimulationsDbContext))]
    [Migration("20250822002215_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Installment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmortizationValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VR_AMORTIZACAO");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("DATEADD(HOUR, -3, GETUTCDATE())");

                    b.Property<short>("InstallmentNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("NUM_PARCELA");

                    b.Property<decimal>("InstallmentValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VR_PARCELA");

                    b.Property<decimal>("InterestValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VR_JUROS");

                    b.Property<long>("SimulationId")
                        .HasColumnType("bigint")
                        .HasColumnName("ID_SIMULACAO");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId");

                    b.ToTable("PARCELAS", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.LoanSimulation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("DATEADD(HOUR, -3, GETUTCDATE())");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("numeric(10,9)")
                        .HasColumnName("TAXA_JUROS");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NO_PRODUTO");

                    b.HasKey("Id");

                    b.ToTable("SIMULACAO_EMPRESTIMO", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.Simulation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("DATEADD(HOUR, -3, GETUTCDATE())");

                    b.Property<long>("LoanSimulationId")
                        .HasColumnType("bigint")
                        .HasColumnName("ID_SIMULACAO_EMPRESTIMO");

                    b.Property<string>("SimulationType")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("TIPO_AMORTIZACAO");

                    b.HasKey("Id");

                    b.HasIndex("LoanSimulationId");

                    b.ToTable("SIMULACOES", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.Installment", b =>
                {
                    b.HasOne("Domain.Entities.Simulation", "Simulation")
                        .WithMany("Installments")
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("Domain.Entities.Simulation", b =>
                {
                    b.HasOne("Domain.Entities.LoanSimulation", "LoanSimulation")
                        .WithMany("Simulations")
                        .HasForeignKey("LoanSimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanSimulation");
                });

            modelBuilder.Entity("Domain.Entities.LoanSimulation", b =>
                {
                    b.Navigation("Simulations");
                });

            modelBuilder.Entity("Domain.Entities.Simulation", b =>
                {
                    b.Navigation("Installments");
                });
#pragma warning restore 612, 618
        }
    }
}
